export const AUTH_COPY = {
    back: 'Back to home',
    oauth: 'Continue with Google',
    divider: 'or',
    genericError: 'Authentication failed. Please try again.',
    signIn: {
        title: 'Welcome back',
        subtitle: 'Sign in to manage your bookings',
        submit: 'Sign In',
        forgot: 'Forgot password?',
        switchPrompt: "Don't have an account?",
        switchAction: 'Sign up',
        submitting: 'Signing in…',
    },
    signUp: {
        title: 'Create your account',
        subtitle: 'Book your first pickup in under a minute',
        submit: 'Create Account',
        switchPrompt: 'Already have an account?',
        switchAction: 'Sign in',
        submitting: 'Creating account…',
        sentTitle: 'Confirm your email',
        sentBody: 'We sent a confirmation link to {email}. Open it to finish signing in.',
        sentNote: 'You can close this page after opening the link.',
    },
    forgotPassword: {
        title: 'Reset your password',
        subtitle: "Enter the email on your account and we'll send a reset link.",
        submit: 'Send reset link',
        sentTitle: 'Check your inbox',
        sentBody: 'If an account exists for {email}, a reset link is on its way.',
        sentNote: 'Use the newest link if you requested more than one.',
        backToSignIn: 'Back to sign in',
        submitting: 'Sending…',
    },
    callback: {
        title: 'Completing sign in',
        subtitle: 'Securely restoring your laundrylo session.',
        errorTitle: 'Sign in could not be completed',
        errorBody: 'The sign-in link is invalid or has expired. Start again to continue.',
        action: 'Back to sign in',
    },
    updatePassword: {
        title: 'Choose a new password',
        subtitle: 'Use at least eight characters.',
        password: 'New Password',
        confirm: 'Confirm New Password',
        submit: 'Update password',
        submitting: 'Updating…',
        mismatch: 'The passwords do not match.',
        tooShort: 'Use at least eight characters.',
        successTitle: 'Password updated',
        successBody: 'Your new password is ready to use.',
        successAction: 'Continue to laundrylo',
        invalidTitle: 'That reset link is not valid',
        invalidBody: 'Request a new password reset link and try again.',
        invalidAction: 'Request another link',
    },
    fields: {
        email: { label: 'Email', placeholder: 'you@example.com', autoComplete: 'email' },
        phone: { label: 'Phone Number', placeholder: '+91 98765 43210', autoComplete: 'tel' },
        fullName: { label: 'Full Name', placeholder: 'Ayush Agrawal', autoComplete: 'name' },
        password: { label: 'Password', placeholder: '••••••••' },
    },
    passwordToggle: { show: 'Show password', hide: 'Hide password' },
} as const;

export const SIGN_UP_FIELDS = [
    { name: 'fullName', type: 'text' },
    { name: 'email', type: 'email' },
    { name: 'phone', type: 'tel' },
] as const;
