export const TAX_RATE = 0.18;

export const CART_COPY = {
    back: 'Back',
    title: 'Your Cart',
    fromPrefix: 'from',
    empty: 'Your cart is empty.',
    browse: 'Browse laundry services',
    summaryTitle: 'Order Summary',
    subtotal: 'Subtotal',
    membership: 'Plus membership',
    discount: 'Plus discount',
    delivery: 'Pickup & Delivery',
    deliveryFree: 'Free',
    taxes: 'Taxes',
    total: 'Total',
    place: 'Place Order',
    clear: 'Clear Cart',
    viewCart: 'View Cart',
    add: 'Add',
    perPrefix: 'per',
} as const;

export const ORDERS_COPY = {
    back: 'Back to home',
    title: 'My Bookings',
    countSuffix: '• Tap an order to track it',
    orderPrefix: 'Order #',
    itemsSuffix: 'items',
    allOrders: 'All Orders',
    orderId: 'Order ID',
    timeline: 'Order Timeline',
    items: 'Items',
    total: 'Total',
    deliveryAddress: 'Delivery Address',
    callSupport: 'Call Support',
    chat: 'Chat',
    servicesSuffix: 'services',
    cancellationTitle: 'Need to cancel?',
    cancellationPolicy:
        'Service-only cash-on-pickup orders can be cancelled until the scheduled pickup. Reserved pickup and delivery capacity is released immediately.',
    cancelOrder: 'Cancel order',
    cancellationConfirmationTitle: 'Cancel this order?',
    cancellationConfirmationBody:
        'This cannot be undone. No payment has been collected, and both reserved time slots will be released.',
    keepOrder: 'Keep order',
    confirmCancellation: 'Yes, cancel order',
    cancelling: 'Cancelling…',
    cancellationFallback: 'The order could not be cancelled. Try again.',
    scheduleTitle: 'Pickup and delivery',
    pickup: 'Pickup',
    delivery: 'Delivery',
    scheduleChanged: 'Schedule last changed',
    reschedulingTitle: 'Need a different time?',
    reschedulingPolicy: 'You can move both appointments to available times until pickup begins.',
    changeSchedule: 'Change schedule',
    choosePickup: 'Choose a new pickup',
    chooseDelivery: 'Choose a new delivery',
    loadingSchedule: 'Loading available times…',
    noReschedulingSlots: 'No alternate times are available in the next two weeks.',
    chooseReschedulingSlots: 'Choose both a pickup and delivery time.',
    saveSchedule: 'Save new schedule',
    savingSchedule: 'Saving…',
    keepSchedule: 'Keep current schedule',
    retrySchedule: 'Try loading times again',
    reschedulingFallback: 'The schedule could not be changed. Try again.',
} as const;

export const PLUS_COPY = {
    back: 'Back to home',
    benefitsTitle: 'What you get',
    alreadyAdded: 'Added to your cart',
    note: 'Activates with your first service order and stays active for one month.',
    cartLabel: 'LaundryLo Plus',
    cartSublabel: 'One-month membership',
    remove: 'Remove LaundryLo Plus',
    needsServices: 'Add laundry services to activate Plus with your first order.',
    browse: 'Browse laundry services',
} as const;
