export const WEEKDAYS = [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
] as const;

export const PARTNER_SETTINGS_COPY = {
    eyebrow: 'Laundry operations',
    title: 'Laundry settings',
    intro: 'Keep your public listing, service areas and availability accurate.',
    portalNavigation: 'Partner portal',
    ordersLink: 'View order queue',
    catalogLink: 'Manage catalogue',
    locationLabel: 'Laundry location',
    profileTitle: 'Public profile',
    profileIntro: 'These details appear on your customer-facing laundry listing.',
    name: 'Laundry name',
    about: 'About this laundry',
    addressTitle: 'Business address',
    addressIntro: 'This is the physical location shown on the customer-facing listing.',
    line1: 'Address line 1',
    line2: 'Address line 2 (optional)',
    city: 'City',
    pincode: 'Business address pincode',
    serviceAreasTitle: 'Service areas',
    serviceAreasIntro:
        'Add every pincode where this laundry accepts pickup and delivery orders. At least one is required.',
    servicePincode: (position: number) => `Service pincode ${position}`,
    addServicePincode: 'Add service pincode',
    remove: 'Remove',
    removeServicePincode: (position: number) => `Remove service pincode ${position}`,
    availabilityTitle: 'Availability',
    availabilityIntro: 'Control new bookings and the hours used to create pickup slots.',
    acceptingOrders: 'Accept new orders',
    acceptingOrdersHelp: 'Turn this off to pause bookings immediately.',
    useOpeningHours: 'Apply weekly opening hours',
    useOpeningHoursHelp: 'When enabled, the listing closes outside the hours below.',
    turnaround: 'Typical turnaround (hours)',
    closuresTitle: 'Holiday closures',
    closuresIntro:
        'Close exceptional dates without changing the weekly schedule. Only today and future dates can be managed here.',
    closuresWarning:
        'Unbooked pickup slots are removed. Existing bookings are kept and must be handled from the order queue.',
    closureDate: (position: number) => `Closure date ${position}`,
    closureReason: (position: number) => `Closure reason ${position} (optional)`,
    closureReasonPlaceholder: 'For example, public holiday',
    addClosure: 'Add holiday closure',
    removeClosure: (position: number) => `Remove holiday closure ${position}`,
    hoursTitle: 'Weekly opening hours',
    hoursIntro: 'Overnight hours are not supported. Mark a day closed instead.',
    closed: 'Closed',
    openingTime: 'Opening time',
    closingTime: 'Closing time',
    currentState: 'Saved customer status',
    openNow: 'Open for bookings now',
    closedNow: 'Closed for bookings now',
    save: 'Save laundry settings',
    saving: 'Saving settings…',
    saved: 'Laundry settings saved.',
    loading: 'Loading laundry settings',
    saveFallback: 'The settings could not be saved. Try again.',
} as const;
